version: "3.9"

services:
  zoom-nginx:
    build:
      args:
        GROUP_ID: $GROUP_ID
        USER_ID: $USER_ID
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    container_name: docker-magento_nginx
    image: ironex/zoom-nginx:1.0.0
    networks:
      - external
      - internal
    ports:
      - 80:8080
    user: $GROUP_ID:$USER_ID
    volumes:
      - ./demo/:/home/dockeruser/zoom/
      - ./zoom-by-ironex.min.js:/home/dockeruser/zoom/js/zoom-by-ironex.min.js
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf

networks:
  internal:
  external: